language: python

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial

install:
  - python setup.py install

script:
  python src/tests/test.py -v
